from local_path import *
from zrst.util import MLF

# ## set paths ###
corpus_path = r'/home/c2tao/mediaeval_2015/data/QUESST2015-dev/Audio/'
target_path = r'/home/c2tao/mediaeval_token/token/mediaeval_1000_active/'
# init generated by matlab/clusterDetection.m
initial_path = r'/home/c2tao/mediaeval_token/init/mediaeval_1000.txt'
continue_path = r'/home/c2tao/mediaeval_token/token/mediaeval_1000_backup_20'
flat_path = r'/home/c2tao/mediaeval_token/init/mediaeval_1000_flatten.txt'


M = MLF(target_path+'result/result.mlf')
